#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ExternalJammingList
    {
        explicit ExternalJammingList(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t jammingType = {};
        std::string className = {};
        std::string windowName = {};
        int32_t fileChecksum = {};
        int32_t fileSize = {};
        int32_t numSpare1 = {};
        std::string internalName = {};
        std::string legalCopyright = {};
        std::string originalFilename = {};
        std::string productionVersion = {};
        std::string comments = {};
        std::string privateBuild = {};
        std::string specialBuild = {};
        std::string spareField = {};
    };

    class ExternalJammingListTable final : public ISoxTable, public std::enable_shared_from_this<ExternalJammingListTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ExternalJammingList*;
        auto Get() const -> const std::vector<ExternalJammingList>&;

    private:
        std::unordered_map<int32_t, ExternalJammingList*> _umap;
        std::vector<ExternalJammingList> _vector;

    };
}
