#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct Hairstyle
    {
        explicit Hairstyle(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t id = {};
        int32_t sex = {};
        int32_t price = {};
    };

    class HairstyleTable final : public ISoxTable, public std::enable_shared_from_this<HairstyleTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const Hairstyle*;
        auto Get() const -> const std::vector<Hairstyle>&;

    private:
        std::unordered_map<int32_t, Hairstyle*> _umap;
        std::vector<Hairstyle> _vector;

    };
}
