#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct HairColor
    {
        explicit HairColor(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t pnxValue = {};
        int32_t r = {};
        int32_t g = {};
        int32_t b = {};
    };

    class HairColorTable final : public ISoxTable, public std::enable_shared_from_this<HairColorTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const HairColor*;
        auto Get() const -> const std::vector<HairColor>&;

    private:
        std::unordered_map<int32_t, HairColor*> _umap;
        std::vector<HairColor> _vector;

    };
}
