#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemmixCorrecttable
    {
        explicit ItemmixCorrecttable(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t difficultyA = {};
        int32_t difficultyB = {};
        int32_t difficultyC = {};
        int32_t difficultyD = {};
        int32_t difficultyE = {};
        int32_t difficultyF = {};
    };

    class ItemmixCorrecttableTable final : public ISoxTable, public std::enable_shared_from_this<ItemmixCorrecttableTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemmixCorrecttable*;
        auto Get() const -> const std::vector<ItemmixCorrecttable>&;

    private:
        std::unordered_map<int32_t, ItemmixCorrecttable*> _umap;
        std::vector<ItemmixCorrecttable> _vector;

    };
}
