#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemmixSkill
    {
        explicit ItemmixSkill(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t iD = {};
        std::string name = {};
        int32_t type = {};
        int32_t difficultyType = {};
        int32_t requiredJobID = {};
        int32_t requiredJobLevel = {};
        int32_t requiredSkillID = {};
        int32_t requiredSkillLevel = {};
        int32_t mixGroupID1 = {};
        int32_t mixGroupID1Level = {};
        int32_t mixGroupID2 = {};
        int32_t mixGroupID2Level = {};
        int32_t mixGroupID3 = {};
        int32_t mixGroupID3Level = {};
        int32_t mixGroupID4 = {};
        int32_t mixGroupID4Level = {};
        int32_t mixGroupID5 = {};
        int32_t mixGroupID5Level = {};
        int32_t mixGroupID6 = {};
        int32_t mixGroupID6Level = {};
        std::string skillDescription = {};
        int32_t maxDepth = {};
        int32_t maxDepthWide1 = {};
        std::string depthName11 = {};
        int32_t depthID11 = {};
        std::string categoryDes11 = {};
        int32_t depthTxID11 = {};
        int32_t depthTxNum11 = {};
        std::string depthName12 = {};
        int32_t depthID12 = {};
        std::string categoryDes12 = {};
        int32_t depthTxID12 = {};
        int32_t depthTxNum12 = {};
        std::string depthName13 = {};
        int32_t depthID13 = {};
        std::string categoryDes13 = {};
        int32_t depthTxID13 = {};
        int32_t depthTxNum13 = {};
        std::string depthName14 = {};
        int32_t depthID14 = {};
        std::string categoryDes14 = {};
        int32_t depthTxID14 = {};
        int32_t depthTxNum14 = {};
        std::string depthName15 = {};
        int32_t depthID15 = {};
        std::string categoryDes15 = {};
        int32_t depthTxID15 = {};
        int32_t depthTxNum15 = {};
        std::string depthName16 = {};
        int32_t depthID16 = {};
        std::string categoryDes16 = {};
        int32_t depthTxID16 = {};
        int32_t depthTxNum16 = {};
        int32_t maxDepthWide2 = {};
        std::string depthName21 = {};
        int32_t depthID21 = {};
        std::string categoryDes21 = {};
        int32_t depthTxID21 = {};
        int32_t depthTxNum21 = {};
        std::string depthName22 = {};
        int32_t depthID22 = {};
        std::string categoryDes22 = {};
        int32_t depthTxID22 = {};
        int32_t depthTxNum22 = {};
        std::string depthName23 = {};
        int32_t depthID23 = {};
        std::string categoryDes23 = {};
        int32_t depthTxID23 = {};
        int32_t depthTxNum23 = {};
        std::string depthName24 = {};
        int32_t depthID24 = {};
        std::string categoryDes24 = {};
        int32_t depthTxID24 = {};
        int32_t depthTxNum24 = {};
        int32_t maxDepthWide3 = {};
        std::string depthName31 = {};
        int32_t depthID31 = {};
        std::string categoryDes31 = {};
        int32_t depthTxID31 = {};
        int32_t depthTxNum31 = {};
        std::string depthName32 = {};
        int32_t depthID32 = {};
        std::string categoryDes32 = {};
        int32_t depthTxID32 = {};
        int32_t depthTxNum32 = {};
        std::string depthName33 = {};
        int32_t depthID33 = {};
        std::string categoryDes33 = {};
        int32_t depthTxID33 = {};
        int32_t depthTxNum33 = {};
        std::string depthName34 = {};
        int32_t depthID34 = {};
        std::string categoryDes34 = {};
        int32_t depthTxID34 = {};
        int32_t depthTxNum34 = {};
    };

    class ItemmixSkillTable final : public ISoxTable, public std::enable_shared_from_this<ItemmixSkillTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemmixSkill*;
        auto Get() const -> const std::vector<ItemmixSkill>&;

    private:
        std::unordered_map<int32_t, ItemmixSkill*> _umap;
        std::vector<ItemmixSkill> _vector;

    };
}
