#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemCombination
    {
        explicit ItemCombination(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t type = {};
        int32_t result = {};
        int32_t job = {};
        int32_t level = {};
        int32_t ability = {};
        int32_t whenFails = {};
        int32_t failExp = {};
        int32_t orgMod1 = {};
        int32_t orgMod2 = {};
        int32_t req1 = {};
        int32_t req2 = {};
        int32_t req3 = {};
        int32_t req4 = {};
        int32_t req5 = {};
        int32_t req6 = {};
        int32_t req7 = {};
        int32_t req8 = {};
        int32_t req9 = {};
        int32_t req1num = {};
        int32_t req2num = {};
        int32_t req3num = {};
        int32_t req4num = {};
        int32_t req5num = {};
        int32_t req6num = {};
        int32_t req7num = {};
        int32_t req8num = {};
        int32_t req9num = {};
    };

    class ItemCombinationTable final : public ISoxTable, public std::enable_shared_from_this<ItemCombinationTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemCombination*;
        auto Get() const -> const std::vector<ItemCombination>&;

    private:
        std::unordered_map<int32_t, ItemCombination*> _umap;
        std::vector<ItemCombination> _vector;

    };
}
