#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemSet
    {
        explicit ItemSet(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t item01 = {};
        int32_t item01Mod = {};
        int32_t item02 = {};
        int32_t item02Mod = {};
        int32_t item03 = {};
        int32_t item03Mod = {};
        int32_t item04 = {};
        int32_t item04Mod = {};
        int32_t item05 = {};
        int32_t item05Mod = {};
        int32_t item06 = {};
        int32_t item06Mod = {};
        int32_t item07 = {};
        int32_t item07Mod = {};
        int32_t item08 = {};
        int32_t item08Mod = {};
        int32_t item09 = {};
        int32_t item09Mod = {};
        int32_t item10 = {};
        int32_t item10Mod = {};
        int32_t item11 = {};
        int32_t item11Mod = {};
        int32_t item12 = {};
        int32_t item12Mod = {};
        int32_t item13 = {};
        int32_t item13Mod = {};
        int32_t item14 = {};
        int32_t item14Mod = {};
        int32_t item15 = {};
        int32_t item15Mod = {};
        int32_t item16 = {};
        int32_t item16Mod = {};
        int32_t item17 = {};
        int32_t item17Mod = {};
        int32_t item18 = {};
        int32_t item18Mod = {};
        int32_t item19 = {};
        int32_t item19Mod = {};
        int32_t item20 = {};
        int32_t item20Mod = {};
        int32_t item21 = {};
        int32_t item21Mod = {};
        int32_t item22 = {};
        int32_t item22Mod = {};
        int32_t item23 = {};
        int32_t item23Mod = {};
        int32_t item24 = {};
        int32_t item24Mod = {};
        int32_t item25 = {};
        int32_t item25Mod = {};
        int32_t item26 = {};
        int32_t item26Mod = {};
        int32_t item27 = {};
        int32_t item27Mod = {};
        int32_t item28 = {};
        int32_t item28Mod = {};
        int32_t item29 = {};
        int32_t item29Mod = {};
        int32_t item30 = {};
        int32_t item30Mod = {};
        int32_t item31 = {};
        int32_t item31Mod = {};
        int32_t item32 = {};
        int32_t item32Mod = {};
        int32_t item33 = {};
        int32_t item33Mod = {};
        int32_t item34 = {};
        int32_t item34Mod = {};
        int32_t item35 = {};
        int32_t item35Mod = {};
        int32_t item36 = {};
        int32_t item36Mod = {};
        int32_t item37 = {};
        int32_t item37Mod = {};
        int32_t item38 = {};
        int32_t item38Mod = {};
        int32_t item39 = {};
        int32_t item39Mod = {};
        int32_t item40 = {};
        int32_t item40Mod = {};
        int32_t item41 = {};
        int32_t item41Mod = {};
        int32_t item42 = {};
        int32_t item42Mod = {};
        int32_t item43 = {};
        int32_t item43Mod = {};
        int32_t item44 = {};
        int32_t item44Mod = {};
        int32_t item45 = {};
        int32_t item45Mod = {};
        int32_t item46 = {};
        int32_t item46Mod = {};
        int32_t item47 = {};
        int32_t item47Mod = {};
        int32_t item48 = {};
        int32_t item48Mod = {};
        int32_t item49 = {};
        int32_t item49Mod = {};
        int32_t item50 = {};
        int32_t item50Mod = {};
    };

    class ItemSetTable final : public ISoxTable, public std::enable_shared_from_this<ItemSetTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemSet*;
        auto Get() const -> const std::vector<ItemSet>&;

    private:
        std::unordered_map<int32_t, ItemSet*> _umap;
        std::vector<ItemSet> _vector;

    };
}
