#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct LevelDiffExp
    {
        explicit LevelDiffExp(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t partyLevelDiffFactor01 = {};
        int32_t partyLevelDiffFactor02 = {};
        int32_t partyLevelDiffFactor03 = {};
        int32_t partyLevelDiffFactor04 = {};
        int32_t partyLevelDiffFactor05 = {};
        int32_t partyLevelDiffFactor06 = {};
        int32_t partyLevelDiffFactor07 = {};
        int32_t partyLevelDiffFactor08 = {};
        int32_t partyLevelDiffFactor09 = {};
        int32_t partyLevelDiffFactor10 = {};
        int32_t partyLevelDiffFactor11 = {};
        int32_t partyLevelDiffFactor12 = {};
        int32_t monsterLevelDiffFactor01 = {};
        int32_t monsterLevelDiffFactor02 = {};
        int32_t monsterLevelDiffFactor03 = {};
        int32_t monsterLevelDiffFactor04 = {};
        int32_t monsterLevelDiffFactor05 = {};
        int32_t monsterLevelDiffFactor06 = {};
        int32_t monsterLevelDiffFactor07 = {};
        int32_t monsterLevelDiffFactor08 = {};
        int32_t monsterLevelDiffFactor09 = {};
        int32_t monsterLevelDiffFactor10 = {};
        int32_t monsterLevelDiffFactor11 = {};
        int32_t monsterLevelDiffFactor12 = {};
        int32_t rareItemDiffFactor01 = {};
        int32_t rareItemDiffFactor02 = {};
        int32_t rareItemDiffFactor03 = {};
        int32_t rareItemDiffFactor04 = {};
        int32_t rareItemDiffFactor05 = {};
        int32_t rareItemDiffFactor06 = {};
        int32_t rareItemDiffFactor07 = {};
        int32_t rareItemDiffFactor08 = {};
        int32_t rareItemDiffFactor09 = {};
        int32_t rareItemDiffFactor10 = {};
        int32_t rareItemDiffFactor11 = {};
        int32_t rareItemDiffFactor12 = {};
    };

    class LevelDiffExpTable final : public ISoxTable, public std::enable_shared_from_this<LevelDiffExpTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const LevelDiffExp*;
        auto Get() const -> const std::vector<LevelDiffExp>&;

    private:
        std::unordered_map<int32_t, LevelDiffExp*> _umap;
        std::vector<LevelDiffExp> _vector;

    };
}
