#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct LvDb
    {
        explicit LvDb(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t job = {};
        int32_t jobStatus = {};
        int32_t power = {};
        int32_t speed = {};
        int32_t health = {};
        int32_t _int = {};
        int32_t will = {};
    };

    class LvDbTable final : public ISoxTable, public std::enable_shared_from_this<LvDbTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const LvDb*;
        auto Get() const -> const std::vector<LvDb>&;

    private:
        std::unordered_map<int32_t, LvDb*> _umap;
        std::vector<LvDb> _vector;

    };
}
