#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct LvExtDb
    {
        explicit LvExtDb(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t ext = {};
    };

    class LvExtDbTable final : public ISoxTable, public std::enable_shared_from_this<LvExtDbTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const LvExtDb*;
        auto Get() const -> const std::vector<LvExtDb>&;

    private:
        std::unordered_map<int32_t, LvExtDb*> _umap;
        std::vector<LvExtDb> _vector;

    };
}
