#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MinigameRank
    {
        explicit MinigameRank(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string rankValue = {};
        std::string rankDesc = {};
    };

    class MinigameRankTable final : public ISoxTable, public std::enable_shared_from_this<MinigameRankTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MinigameRank*;
        auto Get() const -> const std::vector<MinigameRank>&;

    private:
        std::unordered_map<int32_t, MinigameRank*> _umap;
        std::vector<MinigameRank> _vector;

    };
}
