#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MonsterMoveType
    {
        explicit MonsterMoveType(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string movename = {};
        float movespeed = {};
        int32_t gyrationangle1 = {};
        int32_t gyrationangle2 = {};
    };

    class MonsterMoveTypeTable final : public ISoxTable, public std::enable_shared_from_this<MonsterMoveTypeTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MonsterMoveType*;
        auto Get() const -> const std::vector<MonsterMoveType>&;

    private:
        std::unordered_map<int32_t, MonsterMoveType*> _umap;
        std::vector<MonsterMoveType> _vector;

    };
}
