#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MonsterItem
    {
        explicit MonsterItem(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t itemGenFrequency = {};
        int32_t itemsetGenFrequency = {};
        int32_t rareItemGenFrequency = {};
        int32_t rareItemsetGenFrequency = {};
        int32_t itemGoldMod = {};
        int32_t itemGoldMin = {};
        int32_t itemGoldMax = {};
        int32_t item01 = {};
        int32_t item01Mod = {};
        int32_t item02 = {};
        int32_t item02Mod = {};
        int32_t item03 = {};
        int32_t item03Mod = {};
        int32_t item04 = {};
        int32_t item04Mod = {};
        int32_t item05 = {};
        int32_t item05Mod = {};
        int32_t item06 = {};
        int32_t item06Mod = {};
        int32_t item07 = {};
        int32_t item07Mod = {};
        int32_t item08 = {};
        int32_t item08Mod = {};
        int32_t item09 = {};
        int32_t item09Mod = {};
        int32_t item10 = {};
        int32_t item10Mod = {};
        int32_t item11 = {};
        int32_t item11Mod = {};
        int32_t item12 = {};
        int32_t item12Mod = {};
        int32_t item13 = {};
        int32_t item13Mod = {};
        int32_t item14 = {};
        int32_t item14Mod = {};
        int32_t item15 = {};
        int32_t item15Mod = {};
        int32_t item16 = {};
        int32_t item16Mod = {};
        int32_t item17 = {};
        int32_t item17Mod = {};
        int32_t item18 = {};
        int32_t item18Mod = {};
        int32_t item19 = {};
        int32_t item19Mod = {};
        int32_t item20 = {};
        int32_t item20Mod = {};
        int32_t item21 = {};
        int32_t item21Mod = {};
        int32_t item22 = {};
        int32_t item22Mod = {};
        int32_t item23 = {};
        int32_t item23Mod = {};
        int32_t item24 = {};
        int32_t item24Mod = {};
        int32_t item25 = {};
        int32_t item25Mod = {};
        int32_t item26 = {};
        int32_t item26Mod = {};
        int32_t item27 = {};
        int32_t item27Mod = {};
        int32_t item28 = {};
        int32_t item28Mod = {};
        int32_t item29 = {};
        int32_t item29Mod = {};
        int32_t item30 = {};
        int32_t item30Mod = {};
        int32_t itemset01 = {};
        int32_t itemset01Mod = {};
        int32_t itemset02 = {};
        int32_t itemset02Mod = {};
        int32_t itemset03 = {};
        int32_t itemset03Mod = {};
        int32_t itemset04 = {};
        int32_t itemset04Mod = {};
        int32_t itemset05 = {};
        int32_t itemset05Mod = {};
        int32_t itemset06 = {};
        int32_t itemset06Mod = {};
        int32_t itemset07 = {};
        int32_t itemset07Mod = {};
        int32_t itemset08 = {};
        int32_t itemset08Mod = {};
        int32_t itemset09 = {};
        int32_t itemset09Mod = {};
        int32_t itemset10 = {};
        int32_t itemset10Mod = {};
        int32_t rareItem01 = {};
        int32_t rareItem01Mod = {};
        int32_t rareItem02 = {};
        int32_t rareItem02Mod = {};
        int32_t rareItem03 = {};
        int32_t rareItem03Mod = {};
        int32_t rareItem04 = {};
        int32_t rareItem04Mod = {};
        int32_t rareItem05 = {};
        int32_t rareItem05Mod = {};
        int32_t rareItem06 = {};
        int32_t rareItem06Mod = {};
        int32_t rareItem07 = {};
        int32_t rareItem07Mod = {};
        int32_t rareItem08 = {};
        int32_t rareItem08Mod = {};
        int32_t rareItem09 = {};
        int32_t rareItem09Mod = {};
        int32_t rareItem10 = {};
        int32_t rareItem10Mod = {};
        int32_t rareItemset01 = {};
        int32_t rareItemset01Mod = {};
        int32_t rareItemset02 = {};
        int32_t rareItemset02Mod = {};
        int32_t rareItemset03 = {};
        int32_t rareItemset03Mod = {};
        int32_t rareItemset04 = {};
        int32_t rareItemset04Mod = {};
        int32_t rareItemset05 = {};
        int32_t rareItemset05Mod = {};
        int32_t rareItemset06 = {};
        int32_t rareItemset06Mod = {};
        int32_t rareItemset07 = {};
        int32_t rareItemset07Mod = {};
        int32_t rareItemset08 = {};
        int32_t rareItemset08Mod = {};
        int32_t rareItemset09 = {};
        int32_t rareItemset09Mod = {};
        int32_t rareItemset10 = {};
        int32_t rareItemset10Mod = {};
    };

    class MonsterItemTable final : public ISoxTable, public std::enable_shared_from_this<MonsterItemTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MonsterItem*;
        auto Get() const -> const std::vector<MonsterItem>&;

    private:
        std::unordered_map<int32_t, MonsterItem*> _umap;
        std::vector<MonsterItem> _vector;

    };
}
