#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MotionData
    {
        explicit MotionData(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t aniTime = {};
        int32_t hitTime = {};
        int32_t bladeStart = {};
        int32_t bladeEnd = {};
        int32_t attackSound = {};
        int32_t attackDirection = {};
        float damagePercent = {};
        int32_t damageType = {};
        int32_t damageTypePercent = {};
        int32_t targetblowFX = {};
    };

    class MotionDataTable final : public ISoxTable, public std::enable_shared_from_this<MotionDataTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MotionData*;
        auto Get() const -> const std::vector<MotionData>&;

    private:
        std::unordered_map<int32_t, MotionData*> _umap;
        std::vector<MotionData> _vector;

    };
}
