#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct QuestInfo
    {
        explicit QuestInfo(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t descFuncId = {};
        int32_t questCancelable = {};
    };

    class QuestInfoTable final : public ISoxTable, public std::enable_shared_from_this<QuestInfoTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const QuestInfo*;
        auto Get() const -> const std::vector<QuestInfo>&;

    private:
        std::unordered_map<int32_t, QuestInfo*> _umap;
        std::vector<QuestInfo> _vector;

    };
}
