#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ServerListTest
    {
        explicit ServerListTest(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        std::string desc = {};
        std::string ip = {};
    };

    class ServerListTestTable final : public ISoxTable, public std::enable_shared_from_this<ServerListTestTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ServerListTest*;
        auto Get() const -> const std::vector<ServerListTest>&;

    private:
        std::unordered_map<int32_t, ServerListTest*> _umap;
        std::vector<ServerListTest> _vector;

    };
}
