#pragma once

namespace sunlight
{
    ENUM_CLASS(PlayerStatType, int32_t,
        (None, 0)
        // (Gender, 1)
        // (CharLv, 2)
        // (HP, 3)
        // (SP, 4)
        (Str, 5)
        (Dex, 6)
        (Accr, 7)
        (Health, 8)
        (Intell, 9)
        (Wisdom, 10)
        (Will, 11)
        (Unk12, 12)
        (Fire, 13)
        (Water, 14)
        (Lightning, 15)
        (MaxHP, 16)
        (RecoveryRateHP, 17)
        (MaxSP, 18)
        (RecoveryRateSP, 19)
        (Speed, 20)
        (RageUpSpeed, 21)
        (RageDownSpeed, 22)
        (AttackSpeed, 23)
        (AttackDelay, 24)
        (Unk25, 25)
        (Unk26, 26)
        (PhysicalAttackStr, 27)
        (PhysicalAttackDex, 28)
        (PhysicalDefense, 29)
        (Hit, 30)
        (Miss, 31)
        (Critical, 32)
        (Protection, 45)
        (Resistance, 46) // skill cast cancel resistance
        (AttackRange, 47)

        (AttackReflection, 60)
        (AllElemental, 100)
        (AllBaseStat, 101)
        (BaseAttack, 102)
        (RecoveryHPContinue, 1000)
    )
}
