#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct Cafefood
    {
        explicit Cafefood(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string foodName = {};
        int32_t foodModelid = {};
        int32_t foodEatType = {};
        int32_t foodEatCount = {};
        int32_t foodCount = {};
        int32_t foodPrice = {};
        std::string foodDesc = {};
        int32_t foodEffect = {};
        int32_t foodEffectValue = {};
    };

    class CafefoodTable final : public ISoxTable, public std::enable_shared_from_this<CafefoodTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const Cafefood*;
        auto Get() const -> const std::vector<Cafefood>&;

    private:
        std::unordered_map<int32_t, Cafefood*> _umap;
        std::vector<Cafefood> _vector;

    };
}
