#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct DamageSound
    {
        explicit DamageSound(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t matHard = {};
        int32_t matNormal = {};
        int32_t matSoft = {};
        int32_t matReserved1 = {};
        int32_t matReserved2 = {};
        int32_t matReserved3 = {};
    };

    class DamageSoundTable final : public ISoxTable, public std::enable_shared_from_this<DamageSoundTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const DamageSound*;
        auto Get() const -> const std::vector<DamageSound>&;

    private:
        std::unordered_map<int32_t, DamageSound*> _umap;
        std::vector<DamageSound> _vector;

    };
}
