#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct Eventdeffuncserver
    {
        explicit Eventdeffuncserver(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t classId = {};
        int32_t trigger = {};
        int32_t deffuncId = {};
    };

    class EventdeffuncserverTable final : public ISoxTable, public std::enable_shared_from_this<EventdeffuncserverTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const Eventdeffuncserver*;
        auto Get() const -> const std::vector<Eventdeffuncserver>&;

    private:
        std::unordered_map<int32_t, Eventdeffuncserver*> _umap;
        std::vector<Eventdeffuncserver> _vector;

    };
}
