#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemPetFood
    {
        explicit ItemPetFood(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        int32_t generate = {};
        std::string explanation = {};
        int32_t invenWidth = {};
        int32_t invenHeight = {};
        int32_t maxOverlapCount = {};
        int32_t rarity = {};
        int32_t price = {};
        int32_t modelID = {};
        int32_t modelColor = {};
        int32_t dropSound = {};
        int32_t useQuickSlot = {};
        int32_t oneMoreItem = {};
        int32_t petExp = {};
        int32_t petNP = {};
        int32_t petId1 = {};
        int32_t petId2 = {};
        int32_t petId3 = {};
        int32_t ableToSell = {};
        int32_t ableToTrade = {};
        int32_t ableToDrop = {};
        int32_t ableToDestroy = {};
        int32_t ableToStorage = {};
    };

    class ItemPetFoodTable final : public ISoxTable, public std::enable_shared_from_this<ItemPetFoodTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemPetFood*;
        auto Get() const -> const std::vector<ItemPetFood>&;

    private:
        std::unordered_map<int32_t, ItemPetFood*> _umap;
        std::vector<ItemPetFood> _vector;

    };
}
