#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct ItemWeapon
    {
        explicit ItemWeapon(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        int32_t generate = {};
        std::string explanation = {};
        int32_t invenWidth = {};
        int32_t invenHeight = {};
        int32_t maxOverlapCount = {};
        int32_t rarity = {};
        int32_t price = {};
        int32_t modelID = {};
        int32_t modelColor = {};
        int32_t dropSound = {};
        int32_t useQuickSlot = {};
        int32_t oneMoreItem = {};
        int32_t equipPos = {};
        int32_t weaponClass = {};
        int32_t motionCategory1 = {};
        int32_t jobMotion1 = {};
        int32_t motionCategory2 = {};
        int32_t jobMotion2 = {};
        int32_t motionCategory3 = {};
        int32_t jobMotion3 = {};
        int32_t damageType = {};
        int32_t attackType = {};
        int32_t dexBased = {};
        int32_t throwWeapon = {};
        int32_t minimumDamage = {};
        int32_t maximumDamage = {};
        int32_t attackDelay = {};
        int32_t divDamage = {};
        int32_t divDamageDelay = {};
        int32_t combo = {};
        int32_t attackRange = {};
        int32_t useBulletType = {};
        int32_t hitMaterial = {};
        int32_t hitFX1 = {};
        int32_t hitFX2 = {};
        int32_t hitFX3 = {};
        int32_t hitFX4 = {};
        int32_t hitFX5 = {};
        int32_t hitFX6 = {};
        int32_t hitFX7 = {};
        int32_t hitFX8 = {};
        int32_t hitFX9 = {};
        int32_t hitFX10 = {};
        int32_t constraint1 = {};
        int32_t constraint2 = {};
        int32_t constraint3 = {};
        int32_t constraint4 = {};
        int32_t constraint5 = {};
        int32_t constraint6 = {};
        int32_t constraint7 = {};
        int32_t constraint8 = {};
        int32_t constraintValue1 = {};
        int32_t constraintValue2 = {};
        int32_t constraintValue3 = {};
        int32_t constraintValue4 = {};
        int32_t constraintValue5 = {};
        int32_t constraintValue6 = {};
        int32_t constraintValue7 = {};
        int32_t constraintValue8 = {};
        int32_t constraintOR1 = {};
        int32_t constraintOR2 = {};
        int32_t constraintOR3 = {};
        int32_t constraintOR4 = {};
        int32_t constraintOR5 = {};
        int32_t constraintOR6 = {};
        int32_t constraintOR7 = {};
        int32_t equipEffect1 = {};
        int32_t equipEffectValue1 = {};
        int32_t equipEffect2 = {};
        int32_t equipEffectValue2 = {};
        int32_t equipEffect3 = {};
        int32_t equipEffectValue3 = {};
        int32_t equipEffect4 = {};
        int32_t equipEffectValue4 = {};
        int32_t ableToSell = {};
        int32_t ableToTrade = {};
        int32_t ableToDrop = {};
        int32_t ableToDestroy = {};
        int32_t ableToStorage = {};
    };

    class ItemWeaponTable final : public ISoxTable, public std::enable_shared_from_this<ItemWeaponTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const ItemWeapon*;
        auto Get() const -> const std::vector<ItemWeapon>&;

    private:
        std::unordered_map<int32_t, ItemWeapon*> _umap;
        std::vector<ItemWeapon> _vector;

    };
}
