#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct JobReference
    {
        explicit JobReference(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t maxJobLevel = {};
        int32_t commonJobMod = {};
        float mHPFactor = {};
        float mSPFactor = {};
        float pHRatFactor = {};
        float defenseFactor = {};
        float hPRecoveryFactor = {};
        float sPRecoveryFactor = {};
        float avatarSpeedFactor = {};
        std::string comment = {};
    };

    class JobReferenceTable final : public ISoxTable, public std::enable_shared_from_this<JobReferenceTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const JobReference*;
        auto Get() const -> const std::vector<JobReference>&;

    private:
        std::unordered_map<int32_t, JobReference*> _umap;
        std::vector<JobReference> _vector;

    };
}
