#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MiniMap
    {
        explicit MiniMap(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string toolTip = {};
        int32_t icon1 = {};
        int32_t icon2 = {};
    };

    class MiniMapTable final : public ISoxTable, public std::enable_shared_from_this<MiniMapTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MiniMap*;
        auto Get() const -> const std::vector<MiniMap>&;

    private:
        std::unordered_map<int32_t, MiniMap*> _umap;
        std::vector<MiniMap> _vector;

    };
}
