#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct MonsterSkill
    {
        explicit MonsterSkill(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        int32_t routineId = {};
        int32_t passive = {};
        int32_t useType = {};
        int32_t abilityType = {};
        int32_t applyTargetType = {};
        int32_t applyDamageType = {};
        int32_t damageLength = {};
        int32_t damageLength2 = {};
        int32_t damageMaxcount = {};
        int32_t cancelable = {};
        int32_t effect1 = {};
        int32_t effect1Type = {};
        int32_t effect1Reserved1 = {};
        int32_t effect1Reserved2 = {};
        int32_t effect1Reserved3 = {};
        int32_t effect1Reserved4 = {};
        int32_t effect1Reserved5 = {};
        int32_t effect1Reserved6 = {};
        int32_t effect1Reserved7 = {};
        int32_t effect1Reserved8 = {};
        int32_t effect1Reserved9 = {};
        int32_t effect1Reserved10 = {};
        int32_t effect1Reserved11 = {};
        int32_t effect1Reserved12 = {};
        int32_t effect1HopType = {};
        int32_t effect1HopA = {};
        int32_t effect1HopB = {};
        int32_t effect2 = {};
        int32_t effect2Type = {};
        int32_t effect2Reserved1 = {};
        int32_t effect2Reserved2 = {};
        int32_t effect2Reserved3 = {};
        int32_t effect2Reserved4 = {};
        int32_t effect2Reserved5 = {};
        int32_t effect2Reserved6 = {};
        int32_t effect2Reserved7 = {};
        int32_t effect2Reserved8 = {};
        int32_t effect2Reserved9 = {};
        int32_t effect2Reserved10 = {};
        int32_t effect2Reserved11 = {};
        int32_t effect2Reserved12 = {};
        int32_t effect2HopType = {};
        int32_t effect2HopA = {};
        int32_t effect2HopB = {};
        int32_t effect3 = {};
        int32_t effect3Type = {};
        int32_t effect3Reserved1 = {};
        int32_t effect3Reserved2 = {};
        int32_t effect3Reserved3 = {};
        int32_t effect3Reserved4 = {};
        int32_t effect3Reserved5 = {};
        int32_t effect3Reserved6 = {};
        int32_t effect3Reserved7 = {};
        int32_t effect3Reserved8 = {};
        int32_t effect3Reserved9 = {};
        int32_t effect3Reserved10 = {};
        int32_t effect3Reserved11 = {};
        int32_t effect3Reserved12 = {};
        int32_t effect3HopType = {};
        int32_t effect3HopA = {};
        int32_t effect3HopB = {};
        int32_t effect4 = {};
        int32_t effect4Type = {};
        int32_t effect4Reserved1 = {};
        int32_t effect4Reserved2 = {};
        int32_t effect4Reserved3 = {};
        int32_t effect4Reserved4 = {};
        int32_t effect4Reserved5 = {};
        int32_t effect4Reserved6 = {};
        int32_t effect4Reserved7 = {};
        int32_t effect4Reserved8 = {};
        int32_t effect4Reserved9 = {};
        int32_t effect4Reserved10 = {};
        int32_t effect4Reserved11 = {};
        int32_t effect4Reserved12 = {};
        int32_t effect4HopType = {};
        int32_t effect4HopA = {};
        int32_t effect4HopB = {};
    };

    class MonsterSkillTable final : public ISoxTable, public std::enable_shared_from_this<MonsterSkillTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const MonsterSkill*;
        auto Get() const -> const std::vector<MonsterSkill>&;

    private:
        std::unordered_map<int32_t, MonsterSkill*> _umap;
        std::vector<MonsterSkill> _vector;

    };
}
