#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct PetAbility
    {
        explicit PetAbility(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        int32_t abilityType = {};
        int32_t autoAbility = {};
        int32_t delay = {};
        int32_t levelRestriction = {};
    };

    class PetAbilityTable final : public ISoxTable, public std::enable_shared_from_this<PetAbilityTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const PetAbility*;
        auto Get() const -> const std::vector<PetAbility>&;

    private:
        std::unordered_map<int32_t, PetAbility*> _umap;
        std::vector<PetAbility> _vector;

    };
}
