#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct Prop
    {
        explicit Prop(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string name = {};
        int32_t playerActionCategory = {};
        int32_t minRange = {};
        int32_t posX = {};
        int32_t posY = {};
        int32_t posZ = {};
    };

    class PropTable final : public ISoxTable, public std::enable_shared_from_this<PropTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const Prop*;
        auto Get() const -> const std::vector<Prop>&;

    private:
        std::unordered_map<int32_t, Prop*> _umap;
        std::vector<Prop> _vector;

    };
}
