#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct StringTableKorean
    {
        explicit StringTableKorean(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string string = {};
        std::string desc = {};
    };

    class StringTableKoreanTable final : public ISoxTable, public std::enable_shared_from_this<StringTableKoreanTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const StringTableKorean*;
        auto Get() const -> const std::vector<StringTableKorean>&;

    private:
        std::unordered_map<int32_t, StringTableKorean*> _umap;
        std::vector<StringTableKorean> _vector;

    };
}
