#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct StringSubs
    {
        explicit StringSubs(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        std::string org = {};
        std::string subs = {};
    };

    class StringSubsTable final : public ISoxTable, public std::enable_shared_from_this<StringSubsTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const StringSubs*;
        auto Get() const -> const std::vector<StringSubs>&;

    private:
        std::unordered_map<int32_t, StringSubs*> _umap;
        std::vector<StringSubs> _vector;

    };
}
