#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct WeaponAnimationCategory
    {
        explicit WeaponAnimationCategory(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t _default = {};
        int32_t walk = {};
        int32_t run = {};
        int32_t idle = {};
        int32_t disarm = {};
        int32_t rearm = {};
        int32_t attacka = {};
        int32_t attackb = {};
        int32_t attackc = {};
        int32_t attackd = {};
        int32_t reload = {};
        int32_t attackaTime = {};
        int32_t attackbTime = {};
        int32_t attackcTime = {};
        int32_t attackdTime = {};
    };

    class WeaponAnimationCategoryTable final : public ISoxTable, public std::enable_shared_from_this<WeaponAnimationCategoryTable>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const WeaponAnimationCategory*;
        auto Get() const -> const std::vector<WeaponAnimationCategory>&;

    private:
        std::unordered_map<int32_t, WeaponAnimationCategory*> _umap;
        std::vector<WeaponAnimationCategory> _vector;

    };
}
