#pragma once
/**********************************************************
*        AUTO GENERATED FILE BY sox_code_generator        *
*                  DO NOT EDIT THIS FILE                  *
**********************************************************/

#include "sl/data/sox/sox_table_interface.h"

namespace sunlight::sox
{
    struct WhetherForecast3
    {
        explicit WhetherForecast3(StreamReader<std::vector<char>::const_iterator>& reader);

        int32_t index = {};
        int32_t whetherType = {};
        int32_t lightType = {};
        int32_t density = {};
        int32_t cloudType = {};
        int32_t fog = {};
        float fogRate = {};
        int32_t fogColorR = {};
        int32_t fogColorG = {};
        int32_t fogColorB = {};
        int32_t cloudA = {};
        int32_t cloudB = {};
    };

    class WhetherForecast3Table final : public ISoxTable, public std::enable_shared_from_this<WhetherForecast3Table>
    {
    public:
        void LoadFromFile(const std::filesystem::path& path) override;

        auto Find(int32_t index) const -> const WhetherForecast3*;
        auto Get() const -> const std::vector<WhetherForecast3>&;

    private:
        std::unordered_map<int32_t, WhetherForecast3*> _umap;
        std::vector<WhetherForecast3> _vector;

    };
}
