find_package(Boost REQUIRED)
find_package(TBB REQUIRED)
find_package(spdlog REQUIRED)
find_package(Protobuf REQUIRED)
find_package(GTest REQUIRED)
find_package(GTest REQUIRED)
find_package(pugixml CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(unofficial-argon2 CONFIG REQUIRED)
find_package(unofficial-argon2 CONFIG REQUIRED)
find_package(Lua REQUIRED)
find_package(sol2 CONFIG REQUIRED)
